apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-events-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-events-exporter
  template:
    metadata:
      labels:
        app: kube-events-exporter
        metrics: enabled
    spec:
      containers:
        - name: kube-events-exporter
          image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.11
          args:
            - --config=/config/config.yaml
          ports:
            - name: metrics
              containerPort: 9102
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kube-events-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: kube-events-exporter
  namespace: monitoring
  labels:
    metrics: enabled
spec:
  selector:
    app: kube-events-exporter
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
